<?php
/**
 * Bounded WordPress taxonomy reads.
 *
 * @package WPAutoConnector
 */

namespace WPAuto\Connector\Taxonomy;

use WP_Error;
use WP_Term;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Provides strict, bounded category and tag list operations.
 */
final class TaxonomyReadService {
	private const MAX_SEARCH_LENGTH     = 200;
	private const MAX_PER_PAGE          = 50;
	private const MAX_TERM_QUERY_WINDOW = 1000;
	private const QUERY_MARKER          = 'wp_auto_connector_stable_terms_order';

	/**
	 * List categories using the frozen Phase 1.2 contract.
	 *
	 * @param mixed $input Raw ability input.
	 * @return array<string, mixed>|WP_Error
	 */
	public function list_categories( $input = array() ) {
		return $this->list_terms( 'category', true, $input );
	}

	/**
	 * List tags using the frozen Phase 1.2 contract.
	 *
	 * @param mixed $input Raw ability input.
	 * @return array<string, mixed>|WP_Error
	 */
	public function list_tags( $input = array() ) {
		return $this->list_terms( 'post_tag', false, $input );
	}

	/**
	 * Query one fixed taxonomy through a bounded Core term query.
	 *
	 * @param string $taxonomy Fixed built-in taxonomy.
	 * @param bool   $include_parent Whether output includes parent_id.
	 * @param mixed  $input Raw ability input.
	 * @return array<string, mixed>|WP_Error
	 */
	private function list_terms( string $taxonomy, bool $include_parent, $input ) {
		$parameters = $this->normalize_input( $input );
		if ( is_wp_error( $parameters ) ) {
			return $parameters;
		}

		$offset = $this->calculate_offset( $parameters['page'], $parameters['per_page'] );
		if ( is_wp_error( $offset ) ) {
			return $offset;
		}

		if ( $offset > self::MAX_TERM_QUERY_WINDOW - $parameters['per_page'] - 1 ) {
			return $this->pagination_window_exceeded();
		}

		$query_args = array(
			'taxonomy'               => $taxonomy,
			'search'                 => $parameters['search'],
			'number'                 => $parameters['per_page'] + 1,
			'offset'                 => $offset,
			'orderby'                => $this->map_orderby( $parameters['orderby'] ),
			'order'                  => 'asc' === $parameters['order'] ? 'ASC' : 'DESC',
			'hide_empty'             => $parameters['hide_empty'],
			'hierarchical'           => false,
			'pad_counts'             => false,
			'fields'                 => 'all',
			'update_term_meta_cache' => false,
		);

		$use_tie_breaker = 'id' !== $parameters['orderby'];
		if ( $use_tie_breaker ) {
			$query_args[ self::QUERY_MARKER ] = true;
			add_filter( 'terms_clauses', array( $this, 'add_stable_orderby' ), 10, 3 );
		}

		try {
			$terms = get_terms( $query_args );
		} finally {
			if ( $use_tie_breaker ) {
				remove_filter( 'terms_clauses', array( $this, 'add_stable_orderby' ), 10 );
			}
		}

		if ( is_wp_error( $terms ) || ! is_array( $terms ) ) {
			return $this->query_failed();
		}

		$has_more = count( $terms ) > $parameters['per_page'];
		$terms    = array_slice( $terms, 0, $parameters['per_page'] );
		$items    = array();

		foreach ( $terms as $term ) {
			if ( ! $term instanceof WP_Term ) {
				return $this->query_failed();
			}

			$item = array(
				'id'          => (int) $term->term_id,
				'name'        => (string) $term->name,
				'slug'        => (string) $term->slug,
				'description' => (string) $term->description,
				'count'       => (int) $term->count,
			);

			if ( $include_parent ) {
				$item['parent_id'] = (int) $term->parent;
			}

			$items[] = $item;
		}

		return array(
			'items'    => $items,
			'page'     => $parameters['page'],
			'per_page' => $parameters['per_page'],
			'returned' => count( $items ),
			'has_more' => $has_more,
		);
	}

	/**
	 * Add a deterministic term ID tie-breaker to this service's query only.
	 *
	 * @param array<string, string> $clauses SQL clauses generated by Core.
	 * @param array<int, string>    $taxonomies Queried taxonomies.
	 * @param array<string, mixed>  $args Parsed term query arguments.
	 * @return array<string, string>
	 */
	public function add_stable_orderby( array $clauses, array $taxonomies, array $args ): array {
		unset( $taxonomies );

		if ( empty( $args[ self::QUERY_MARKER ] ) || empty( $clauses['orderby'] ) ) {
			return $clauses;
		}

		$direction          = isset( $args['order'] ) && 'DESC' === strtoupper( (string) $args['order'] ) ? 'DESC' : 'ASC';
		$clauses['orderby'] = $clauses['orderby'] . ' ' . $direction . ', t.term_id';

		return $clauses;
	}

	/**
	 * Apply frozen defaults and reject values outside the public schema.
	 *
	 * @param mixed $input Raw list input.
	 * @return array<string, bool|int|string>|WP_Error
	 */
	private function normalize_input( $input ) {
		if ( null === $input ) {
			$input = array();
		}

		if ( ! is_array( $input ) ) {
			return $this->invalid_request();
		}

		$allowed_keys = array( 'search', 'page', 'per_page', 'orderby', 'order', 'hide_empty' );
		if ( array_diff( array_keys( $input ), $allowed_keys ) ) {
			return $this->invalid_request();
		}

		$parameters = array_merge(
			array(
				'search'     => '',
				'page'       => 1,
				'per_page'   => 20,
				'orderby'    => 'name',
				'order'      => 'asc',
				'hide_empty' => false,
			),
			$input
		);

		if (
			! is_string( $parameters['search'] )
			|| ! is_int( $parameters['page'] )
			|| $parameters['page'] < 1
			|| ! is_int( $parameters['per_page'] )
			|| $parameters['per_page'] < 1
			|| $parameters['per_page'] > self::MAX_PER_PAGE
			|| ! is_string( $parameters['orderby'] )
			|| ! in_array( $parameters['orderby'], array( 'name', 'count', 'id', 'slug' ), true )
			|| ! is_string( $parameters['order'] )
			|| ! in_array( $parameters['order'], array( 'asc', 'desc' ), true )
			|| ! is_bool( $parameters['hide_empty'] )
		) {
			return $this->invalid_request();
		}

		$search_length = function_exists( 'mb_strlen' )
			? mb_strlen( $parameters['search'] )
			: strlen( $parameters['search'] );

		if ( $search_length > self::MAX_SEARCH_LENGTH ) {
			return $this->invalid_request();
		}

		return $parameters;
	}

	/**
	 * Calculate a safe query offset.
	 *
	 * @param int $page Requested page.
	 * @param int $per_page Effective bounded page size.
	 * @return int|WP_Error
	 */
	private function calculate_offset( int $page, int $per_page ) {
		if ( ( $page - 1 ) > intdiv( PHP_INT_MAX, $per_page ) ) {
			return $this->invalid_request();
		}

		$offset = ( $page - 1 ) * $per_page;
		if ( $offset > PHP_INT_MAX - $per_page - 1 ) {
			return $this->invalid_request();
		}

		return $offset;
	}

	/**
	 * Map a public order key to a known-safe Core field.
	 *
	 * @param string $orderby Public ordering value.
	 */
	private function map_orderby( string $orderby ): string {
		return 'id' === $orderby ? 'term_id' : $orderby;
	}

	/**
	 * Return the stable invalid-input error.
	 */
	private function invalid_request(): WP_Error {
		return new WP_Error(
			'wp_auto_invalid_request',
			__( 'The request parameters are invalid.', 'wp-auto-connector' ),
			array( 'status' => 400 )
		);
	}

	/**
	 * Return the stable bounded-pagination error.
	 */
	private function pagination_window_exceeded(): WP_Error {
		return new WP_Error(
			'wp_auto_pagination_window_exceeded',
			__( 'The requested page exceeds the supported search window.', 'wp-auto-connector' ),
			array( 'status' => 400 )
		);
	}

	/**
	 * Return a generic taxonomy query failure without internal details.
	 */
	private function query_failed(): WP_Error {
		return new WP_Error(
			'wp_auto_taxonomy_query_failed',
			__( 'The taxonomy terms could not be retrieved.', 'wp-auto-connector' ),
			array( 'status' => 500 )
		);
	}
}
