<?php
/**
 * Build the private MCP Adapter runtime from the locked Composer packages.
 *
 * @package WPAutoConnector
 */

declare(strict_types=1);

$project_root = dirname(__DIR__);
$vendor_root  = $project_root . DIRECTORY_SEPARATOR . 'vendor';
$target_root  = $vendor_root . DIRECTORY_SEPARATOR . 'wp-auto-mcp-runtime';
$lock_file    = $project_root . DIRECTORY_SEPARATOR . 'composer.lock';

if (! is_file($lock_file)) {
	fwrite(STDERR, "composer.lock is required to build the private MCP runtime.\n");
	exit(1);
}

$lock = json_decode((string) file_get_contents($lock_file), true);
if (! is_array($lock) || ! isset($lock['packages']) || ! is_array($lock['packages'])) {
	fwrite(STDERR, "composer.lock could not be parsed.\n");
	exit(1);
}

$required_versions = array(
	'wordpress/mcp-adapter'  => '0.6.1',
	'wordpress/php-mcp-schema' => '0.1.3',
);
$locked_versions = array();

foreach ($lock['packages'] as $package) {
	if (! is_array($package) || ! isset($package['name'], $package['version'])) {
		continue;
	}
	$name = (string) $package['name'];
	if (isset($required_versions[$name])) {
		$locked_versions[$name] = ltrim((string) $package['version'], 'v');
	}
}

foreach ($required_versions as $package => $required_version) {
	if (($locked_versions[$package] ?? '') !== $required_version) {
		fwrite(STDERR, sprintf("Expected %s %s in composer.lock.\n", $package, $required_version));
		exit(1);
	}
}

$sources = array(
	'mcp-adapter' => $vendor_root . DIRECTORY_SEPARATOR . 'wordpress' . DIRECTORY_SEPARATOR . 'mcp-adapter' . DIRECTORY_SEPARATOR . 'includes',
	'php-mcp-schema' => $vendor_root . DIRECTORY_SEPARATOR . 'wordpress' . DIRECTORY_SEPARATOR . 'php-mcp-schema' . DIRECTORY_SEPARATOR . 'src',
);

foreach ($sources as $source) {
	if (! is_dir($source)) {
		fwrite(STDERR, sprintf("Missing installed Composer source: %s\n", $source));
		exit(1);
	}
}

/**
 * Remove one generated directory after verifying that it is inside vendor.
 */
function wp_auto_remove_generated_directory(string $path, string $vendor_root): void {
	$normalized_vendor = rtrim(str_replace('\\', '/', $vendor_root), '/');
	$normalized_path   = str_replace('\\', '/', $path);
	if (strpos($normalized_path, $normalized_vendor . '/wp-auto-mcp-runtime') !== 0) {
		throw new RuntimeException('Refusing to remove a path outside the private runtime target.');
	}
	if (! is_dir($path)) {
		return;
	}
	$iterator = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS),
		RecursiveIteratorIterator::CHILD_FIRST
	);
	foreach ($iterator as $item) {
		if ($item->isDir()) {
			rmdir($item->getPathname());
		} else {
			unlink($item->getPathname());
		}
	}
	rmdir($path);
}

/**
 * Prefix only the two locked WordPress package namespaces and private hooks.
 */
function wp_auto_transform_mcp_source(string $contents): string {
	$contents = str_replace(
		array('WP\\McpSchema', 'WP\\MCP'),
		array('WPAuto\\Connector\\PrivateMcp\\WP\\McpSchema', 'WPAuto\\Connector\\PrivateMcp\\WP\\MCP'),
		$contents
	);
	$contents = str_replace('mcp_adapter_', 'wp_auto_connector_mcp_adapter_', $contents);
	return preg_replace(
		"/(\\\\WP_CLI::add_command\\(\\s*)'mcp-adapter'/",
		"$1'wp-auto-mcp-adapter'",
		$contents
	) ?? $contents;
}

/**
 * Copy and transform one source tree.
 */
function wp_auto_copy_private_tree(string $source, string $destination): void {
	$iterator = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($source, FilesystemIterator::SKIP_DOTS),
		RecursiveIteratorIterator::SELF_FIRST
	);
	foreach ($iterator as $item) {
		$relative = substr($item->getPathname(), strlen($source) + 1);
		$target   = $destination . DIRECTORY_SEPARATOR . $relative;
		if ($item->isDir()) {
			if (! is_dir($target) && ! mkdir($target, 0777, true) && ! is_dir($target)) {
				throw new RuntimeException(sprintf('Could not create %s.', $target));
			}
			continue;
		}
		$contents = (string) file_get_contents($item->getPathname());
		if ('php' === strtolower((string) pathinfo($target, PATHINFO_EXTENSION))) {
			$contents = wp_auto_transform_mcp_source($contents);
		}
		if (false === file_put_contents($target, $contents)) {
			throw new RuntimeException(sprintf('Could not write %s.', $target));
		}
	}
}

try {
	wp_auto_remove_generated_directory($target_root, $vendor_root);
	if (! mkdir($target_root, 0777, true) && ! is_dir($target_root)) {
		throw new RuntimeException('Could not create the private runtime directory.');
	}

	foreach ($sources as $name => $source) {
		$destination = $target_root . DIRECTORY_SEPARATOR . $name;
		mkdir($destination, 0777, true);
		wp_auto_copy_private_tree($source, $destination);
	}

	$autoload = <<<'PHP'
<?php
/** Private MCP runtime autoloader. Generated by tools/build-mcp-runtime.php. */
spl_autoload_register(
	static function (string $class): void {
		$maps = array(
			'WPAuto\\Connector\\PrivateMcp\\WP\\MCP\\' => __DIR__ . '/mcp-adapter/',
			'WPAuto\\Connector\\PrivateMcp\\WP\\McpSchema\\' => __DIR__ . '/php-mcp-schema/',
		);
		foreach ($maps as $prefix => $directory) {
			if (0 !== strncmp($class, $prefix, strlen($prefix))) {
				continue;
			}
			$file = $directory . str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
			if (is_readable($file)) {
				require_once $file;
			}
			return;
		}
	}
);
PHP;
	file_put_contents($target_root . DIRECTORY_SEPARATOR . 'autoload.php', $autoload . PHP_EOL);

	$manifest = array(
		'generated_by' => 'tools/build-mcp-runtime.php',
		'namespace_prefix' => 'WPAuto\\Connector\\PrivateMcp',
		'private_hook_prefix' => 'wp_auto_connector_mcp_adapter_',
		'packages' => $required_versions,
	);
	file_put_contents(
		$target_root . DIRECTORY_SEPARATOR . 'manifest.json',
		json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL
	);

	copy(
		$vendor_root . DIRECTORY_SEPARATOR . 'wordpress' . DIRECTORY_SEPARATOR . 'mcp-adapter' . DIRECTORY_SEPARATOR . 'LICENSE.md',
		$target_root . DIRECTORY_SEPARATOR . 'LICENSE-MCP-ADAPTER.md'
	);
	copy(
		$vendor_root . DIRECTORY_SEPARATOR . 'wordpress' . DIRECTORY_SEPARATOR . 'php-mcp-schema' . DIRECTORY_SEPARATOR . 'LICENSE.md',
		$target_root . DIRECTORY_SEPARATOR . 'LICENSE-PHP-MCP-SCHEMA.md'
	);
} catch (Throwable $error) {
	fwrite(STDERR, $error->getMessage() . PHP_EOL);
	exit(1);
}

fwrite(STDOUT, "Built private MCP Adapter 0.6.1 runtime.\n");
